# Let NetworkManager manage all devices on this system

network:
  version:  2
  renderer: NetworkManager
  ethernets:
    enxxxx: # set your interface name
      dhcp4:  no
      dhcp6:  no
      addresses:  [192.168.101.xx/23] # set your IP address
      gateway4: 192.168.100.1
      nameservers:
        addresses:  [192.168.100.1, 8.8.8.8]
